In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv("/home/darkcover/Documentos/Out/dados/odds_200k.csv")
dados.head()

   Unnamed: 0   Odd  Odd_Categoria  odd_entrada
0           0  3.85              9         11.0
1           1  6.96             10          9.0
2           2  5.41             10         10.0
3           3  1.05              2         10.0
4           4  1.70              6          2.0

In [4]:
data_symbol = dados['Odd_Categoria']

In [5]:
data_symbol = data_symbol.tail(500).reset_index(drop=True)

In [6]:
data_symbol.to_csv('/home/darkcover/Documentos/Out/dados/estudo.csv')

In [8]:
geral_cat = []
for name in dados['Odd']:
  #print(name)
  if name < 1.05:
    geral_cat.append(1)
  elif name >= 1.05 and name < 1.15:
    geral_cat.append(2)
  elif name >= 1.15 and name < 1.3:
    geral_cat.append(3)
  elif name >= 1.3 and name < 1.45:
    geral_cat.append(4)
  elif name >= 1.45 and name < 1.7:
    geral_cat.append(5)
  elif name >= 1.7 and name < 2.1:
    geral_cat.append(6)
  elif name >= 2.1 and name < 2.6:
    geral_cat.append(7)
  elif name >= 2.6 and name < 3.5:
    geral_cat.append(8)
  elif name >= 3.5 and name < 5:
    geral_cat.append(9)
  elif name >= 5:
    geral_cat.append(10)

print(len(geral_cat))
geral_cat1 = pd.DataFrame([geral_cat]).T
geral_cat1.columns = ['Odd_Categoria1']
geral_cat1 = geral_cat1.tail(500).reset_index(drop=True)
geral_cat1.to_csv('/home/darkcover/Documentos/Out/dados/estudo1.csv')
data = pd.concat([dados, geral_cat1], axis = 1)

data['Odd_Categoria1'].describe()

199999

count    500.00000
mean       6.20000
std        2.89703
min        1.00000
25%        4.00000
50%        6.00000
75%        9.00000
max       10.00000
Name: Odd_Categoria1, dtype: float64

In [9]:
geral_cat = []
for name in dados['Odd']:
  #print(name)
  if name < 1.15:
    geral_cat.append(1)
  elif name >= 1.15 and name < 1.3:
    geral_cat.append(2)
  elif name >= 1.3 and name < 1.45:
    geral_cat.append(3)
  elif name >= 1.45 and name < 1.7:
    geral_cat.append(4)
  elif name >= 1.7 and name < 2.1:
    geral_cat.append(5)
  elif name >= 2.1 and name < 2.6:
    geral_cat.append(6)
  elif name >= 2.6 and name < 3.5:
    geral_cat.append(7)
  elif name >= 3.5 and name < 5:
    geral_cat.append(8)
  elif name >= 5:
    geral_cat.append(9)

print(len(geral_cat))
geral_cat1 = pd.DataFrame([geral_cat]).T
geral_cat1.columns = ['Odd_Categoria2']
geral_cat1 = geral_cat1.tail(500).reset_index(drop=True)
geral_cat1.to_csv('/home/darkcover/Documentos/Out/dados/estudo2.csv')
data = pd.concat([dados, geral_cat1], axis = 1)

data['Odd_Categoria2'].describe()

199999

count    500.000000
mean       5.262000
std        2.793737
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max        9.000000
Name: Odd_Categoria2, dtype: float64

In [10]:
geral_cat = []
for name in dados['Odd']:
  #print(name)
  if name < 1.15:
    geral_cat.append(1)
  elif name >= 1.15 and name < 1.3:
    geral_cat.append(2)
  elif name >= 1.3 and name < 1.45:
    geral_cat.append(3)
  elif name >= 1.45 and name < 1.7:
    geral_cat.append(4)
  elif name >= 1.7 and name < 2.1:
    geral_cat.append(5)
  elif name >= 2.1 and name < 2.6:
    geral_cat.append(6)
  elif name >= 2.6 and name < 3.5:
    geral_cat.append(7)
  elif name >= 3.5:
    geral_cat.append(8)

print(len(geral_cat))
geral_cat1 = pd.DataFrame([geral_cat]).T
geral_cat1.columns = ['Odd_Categoria3']
geral_cat1 = geral_cat1.tail(500).reset_index(drop=True)
geral_cat1.to_csv('/home/darkcover/Documentos/Out/dados/estudo3.csv')
data = pd.concat([dados, geral_cat1], axis = 1)

data['Odd_Categoria3'].describe()

199999

count    500.000000
mean       5.054000
std        2.532175
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max        8.000000
Name: Odd_Categoria3, dtype: float64

In [11]:
geral_cat = []
for name in dados['Odd']:
  #print(name)
  if name < 1.3:
    geral_cat.append(1)
  elif name >= 1.3 and name < 1.45:
    geral_cat.append(2)
  elif name >= 1.45 and name < 1.7:
    geral_cat.append(3)
  elif name >= 1.7 and name < 2.1:
    geral_cat.append(4)
  elif name >= 2.1 and name < 2.6:
    geral_cat.append(5)
  elif name >= 2.6 and name < 3.5:
    geral_cat.append(6)
  elif name >= 3.5:
    geral_cat.append(7)

print(len(geral_cat))
geral_cat1 = pd.DataFrame([geral_cat]).T
geral_cat1.columns = ['Odd_Categoria4']
geral_cat1 = geral_cat1.tail(500).reset_index(drop=True)
geral_cat1.to_csv('/home/darkcover/Documentos/Out/dados/estudo4.csv')
data = pd.concat([dados, geral_cat1], axis = 1)

data['Odd_Categoria4'].describe()

199999

count    500.000000
mean       4.182000
std        2.341761
min        1.000000
25%        2.000000
50%        4.000000
75%        7.000000
max        7.000000
Name: Odd_Categoria4, dtype: float64

In [12]:
geral_cat = []
for name in dados['Odd']:
  #print(name)
  if name < 1.3:
    geral_cat.append(1)
  elif name >= 1.3 and name < 1.45:
    geral_cat.append(2)
  elif name >= 1.45 and name < 1.7:
    geral_cat.append(3)
  elif name >= 1.7 and name < 2.1:
    geral_cat.append(4)
  elif name >= 2.1 and name < 2.6:
    geral_cat.append(5)
  elif name >= 2.6:
    geral_cat.append(6)

print(len(geral_cat))
geral_cat1 = pd.DataFrame([geral_cat]).T
geral_cat1.columns = ['Odd_Categoria5']
geral_cat1 = geral_cat1.tail(500).reset_index(drop=True)
geral_cat1.to_csv('/home/darkcover/Documentos/Out/dados/estudo5.csv')


data = pd.concat([dados, geral_cat1], axis = 1)


data['Odd_Categoria5'].describe()

199999

count    500.000000
mean       3.902000
std        2.025983
min        1.000000
25%        2.000000
50%        4.000000
75%        6.000000
max        6.000000
Name: Odd_Categoria5, dtype: float64

In [3]:
dados1 = pd.read_csv('/home/darkcover/Documentos/Out/dados/metricas_aposta.csv')
dados1

,epoch_accuracies,epoch_directional_accuracies,epoch_weighted_directional_accuracies
0,1.9909,3.9622,5.9531
1,2.0031,3.9649,5.9680
2,1.9990,3.9619,5.9609
3,1.9716,3.9611,5.9327
4,2.0079,3.9625,5.9704
5,1.9737,3.9616,5.9353
6,1.9906,3.9616,5.9522
7,2.0076,3.9599,5.9675
8,2.0357,3.9613,5.9970
9,2.0659,3.9602,6.0261
10,2.0719,3.9613,6.0332
11,2.0078,3.9604,5.9682
12,2.0475,3.9583,6.0058
13,2.0475,3.9624,6.0099
14,2.0387,3.9654,6.0041
15,1.9700,3.9645,5.9345
16,2.0409,3.9612,6.0021
17,2.0022,3.9611,5.9633
18,2.1726,3.9587,6.1313
19,2.0659,3.9619,6.0278
20,2.1211,3.9613,6.0824
21,2.1205,3.9657,6.0862
22,2.1049,3.9637,6.0686
23,2.1265,3.9615,6.0880
24,2.0829,3.9594,6.0423

In [4]:
dados2 = pd.read_csv('/home/darkcover/Documentos/Out/dados/metricas_aposta.csv')
dados2

,epoch_accuracies,epoch_directional_accuracies,epoch_weighted_directional_accuracies
0,1.895,3.985,5.880
1,2.125,3.995,6.120
2,2.020,3.995,6.015
3,2.030,3.985,6.015
4,2.020,3.990,6.010
5,1.920,3.985,5.905
6,1.955,3.990,5.945
7,2.095,3.985,6.080
8,1.930,3.990,5.920
9,1.945,3.995,5.940
10,1.985,3.990,5.975
11,2.095,3.980,6.075
12,2.250,3.990,6.240
13,2.005,3.995,6.000
14,2.055,3.985,6.040
15,1.905,3.995,5.900
16,2.055,3.985,6.040
17,1.895,3.990,5.885
18,2.025,3.995,6.020
19,1.955,3.985,5.940
20,2.035,3.980,6.015
21,1.980,3.985,5.965
22,2.080,3.980,6.060
23,1.920,3.990,5.910
24,2.035,3.990,6.025

In [5]:
dados3 = pd.read_csv('/home/darkcover/Documentos/Out/dados/metricas_aposta.csv')
dados3

,epoch_accuracies,epoch_directional_accuracies,epoch_weighted_directional_accuracies
0,2.001,3.967,5.968
1,1.914,3.965,5.879
2,2.038,3.966,6.004
3,2.052,3.963,6.015
4,1.957,3.968,5.925
5,1.925,3.966,5.891
6,1.995,3.960,5.955
7,1.964,3.963,5.927
8,1.950,3.965,5.915
9,1.982,3.968,5.950
10,2.069,3.968,6.037
11,1.948,3.972,5.920
12,1.908,3.966,5.874
13,1.945,3.973,5.918
14,1.920,3.969,5.889
15,1.918,3.969,5.887
16,1.908,3.971,5.879
17,1.878,3.968,5.846
18,1.948,3.969,5.917
19,1.951,3.971,5.922
20,1.887,3.969,5.856
21,1.947,3.972,5.919
22,1.990,3.960,5.950
23,1.972,3.961,5.933
24,1.877,3.967,5.844

In [6]:
dados4 = pd.read_csv('/home/darkcover/Documentos/Out/dados/metricas_aposta.csv')
dados4

,epoch_accuracies,epoch_directional_accuracies,epoch_weighted_directional_accuracies
0,1.9505,3.9525,5.9030
1,2.0125,3.9545,5.9670
2,2.0225,3.9580,5.9805
3,2.0130,3.9595,5.9725
4,2.0550,3.9570,6.0120
5,2.0455,3.9480,5.9935
6,1.9785,3.9550,5.9335
7,1.9925,3.9575,5.9500
8,1.9405,3.9570,5.8975
9,2.0345,3.9525,5.9870
10,2.0525,3.9545,6.0070
11,1.9140,3.9520,5.8660
12,1.9460,3.9535,5.8995
13,1.9295,3.9555,5.8850
14,1.9455,3.9570,5.9025
15,1.8850,3.9580,5.8430
16,1.9990,3.9530,5.9520
17,2.0015,3.9510,5.9525
18,2.0860,3.9545,6.0405
19,1.9555,3.9500,5.9055
20,2.0700,3.9475,6.0175
21,1.9110,3.9525,5.8635
22,2.0730,3.9535,6.0265
23,2.1950,3.9445,6.1395
24,2.1960,3.9495,6.1455